version: '3.8'

services:

  backend:
    build: ./be-edu-stats
    ports:
      - 5000:5000
    volumes:
      - ./be-edu-stats:/app
    command: python main.py
    restart: always

  frontend:
    depends_on:
      - backend
    build: ./fe-edu-stats
    volumes:
      - './fe-edu-stats:/app'
    ports:
      - 9000:4173
    restart: always