version: '3.8'

services:

  backend:
    build: ./be-edu-stats
    ports:
      - 5000:5000
    volumes:
      - ./be-edu-stats:/app
    command: python main.py

  frontend:
    build: ./fe-edu-stats
    volumes:
      - './fe-edu-stats:/app'
      # - '/app/node_modules'
    ports:
      - 9000:4173